In [19]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40,101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))


#scores_df.T  #轉置

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values   #第一層[]是subscript,第二層[]才是list
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]   #變換欄位
#scores_df

#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]  #silce

     姓名 性別  國文  英文  數學  地理  歷史
6   朱冠霖  男  78  96  81  58  84
7   謝欣蓉  女  59  65  63  81  73
8   羅淑芬  女  49  49  66  78  71
9   許美慧  女  51  52  52  87  97
10  廖志豪  男  52  48  56  82  90

In [ ]:
# 透過值來收尋
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]

     姓名 性別  國文  英文  數學  地理  歷史
7   謝欣蓉  女  59  65  63  81  73
8   羅淑芬  女  49  49  66  78  71
9   許美慧  女  51  52  52  87  97
10  廖志豪  男  52  48  56  82  90
16  莊承翰  男  56  62  46  91  54
19  呂婉慧  女  59  52  65  55  68
22  李柏融  男  51  48  70  53  76
23  曾明軒  男  46  41  77  90  80
25  洪怡君  女  40  63  58  61  70
43  吳雅萍  女  57  46  60  51  90
45  莊柏融  男  54  88  89  88  67
48  劉婉婷  女  40  42  85  87  44