In [65]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40,101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))


#scores_df.T  #轉置

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values   #第一層[]是subscript,第二層[]才是list
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]   #變換欄位
#scores_df

#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]  #silce

     姓名 性別  國文  英文  數學  地理  歷史
6   朱冠霖  男  67  54  71  59  89
7   謝欣蓉  女  80  67  92  41  47
8   羅淑芬  女  41  96  89  62  76
9   許美慧  女  96  98  93  54  46
10  廖志豪  男  62  67  40  72  49

In [66]:
# 透過值來搜尋
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]
scores_df.query("性別 == '女' and 國文 < 60")

     姓名 性別  國文  英文  數學  地理  歷史
8   羅淑芬  女  41  96  89  62  76
15  王婉茹  女  50  92  53  91  58
19  呂婉慧  女  48  96  70  58  64
27  江雅琪  女  42  85  46  74  54
30  楊靜宜  女  51  59  44  92  97
32  蕭怡伶  女  40  56  85  54  88

In [67]:
# 統計
scores_df["總分"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)  # axis=1：橫向加總
scores_df["平均"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_df["排名"] = scores_df['總分'].rank(ascending = False, method = 'min')
scores_df.sort_values(by="排名")

     姓名 性別   國文  英文  數學  地理   歷史   總分    平均    排名
26  洪柏宏  男   51  72  97  98   95  413  82.6   1.0
46  鍾浩銘  男   99  91  95  74   54  413  82.6   1.0
39  彭美慧  女   75  47  95  89   96  402  80.4   3.0
29  簡婉慧  女   61  89  87  88   74  399  79.8   4.0
48  劉婉婷  女   88  91  62  60   93  394  78.8   5.0
13  蘇雅婷  女   99  96  40  68   89  392  78.4   6.0
23  曾明軒  男   98  61  88  72   69  388  77.6   7.0
9   許美慧  女   96  98  93  54   46  387  77.4   8.0
21  蘇彥宏  男  100  86  83  42   71  382  76.4   9.0
34  簡建宏  男  100  62  74  71   74  381  76.2  10.0
28  郭怡萱  女   83  68  88  96   42  377  75.4  11.0
3   吳子睿  男   63  85  50  96   71  365  73.0  12.0
20  莊子謙  男   83  97  71  43   71  365  73.0  12.0
8   羅淑芬  女   41  96  89  62   76  364  72.8  14.0
24  呂佳瑩  女   90  89  61  41   80  361  72.2  15.0
38  邱宗翰  男   53  96  66  47   99  361  72.2  15.0
31  曾靜儀  女   65  59  67  90   74  355  71.0  17.0
47  周美玲  女   73  72  93  61   53  352  70.4  18.0
43  吳雅萍  女   70  86  97  42   54  349  69.8  19.0
15  王婉茹  女   50  92  53  91   58  344  68.8  20.0
30  楊靜宜  女   51  59  44  92   97  343  68.6  21.0
1   劉彥宏  男   88  50  51  54  100  343  68.6  21.0
11  葉柏翰  男   53  88  48  69   84  342  68.4  23.0
6   朱冠霖  男   67  54  71  59   89  340  68.0  24.0
36  蕭浩宇  男   77  45  89  60   66  337  67.4  25.0
25  洪怡君  女   66  64  62  53   91  336  67.2  26.0
19  呂婉慧  女   48  96  70  58   64  336  67.2  26.0
2   曾彥廷  男   54  92  60  50   76  332  66.4  28.0
7   謝欣蓉  女   80  67  92  41   47  327  65.4  29.0
32  蕭怡伶  女   40  56  85  54   88  323  64.6  30.0
22  李柏融  男   58  80  58  53   73  322  64.4  31.0
4   蕭志明  男   61  53  64  94   45  317  63.4  32.0
35  劉浩然  男   47  58  90  65   56  316  63.2  33.0
16  莊承翰  男   69  56  46  53   92  316  63.2  33.0
14  高浩宇  男   47  48  68  70   82  315  63.0  35.0
45  莊柏融  男   60  75  72  52   54  313  62.6  36.0
17  黃裕傑  男   58  60  73  53   65  309  61.8  37.0
5   王文傑  男   57  45  49  61   90  302  60.4  38.0
37  呂怡靜  女   94  46  54  64   44  302  60.4  38.0
27  江雅琪  女   42  85  46  74   54  301  60.2  40.0
40  劉靜芬  女   67  71  73  46   44  301  60.2  40.0
44  施子軒  男   69  61  58  69   43  300  60.0  42.0
49  曾明哲  男   47  72  75  47   55  296  59.2  43.0
12  呂承恩  男   42  55  75  43   79  294  58.8  44.0
50  詹柏翰  男   55  58  41  78   61  293  58.6  45.0
33  洪裕豪  男   64  51  42  67   68  292  58.4  46.0
10  廖志豪  男   62  67  40  72   49  290  58.0  47.0
42  邱裕豪  男   41  59  65  60   42  267  53.4  48.0
18  王冠廷  男   54  73  45  45   41  258  51.6  49.0
41  許淑芬  女   68  42  40  43   60  253  50.6  50.0

In [68]:
from pandas import Series
def calculate(s:Series) -> int:
    #print(s)
    #print((~(s < 60)).sum())  #計算不及格的科目數
    n = (s < 60).sum()    #計算及格的科目數
    m = (~(s < 60)).sum()
    return n,m

#scores_df['及格的科目數'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(calulate,axis=1)
#scores_df['不及格的科目數'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(calulate,axis=1)
#scores_df
#修改
result = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(calculate, axis=1, result_type='expand')
result.columns = ['及格的科目數', '不及格的科目數']
scores_df = pd.concat([scores_df, result], axis=1)
scores_df

     姓名 性別   國文  英文  數學  地理   歷史   總分    平均    排名  及格的科目數  不及格的科目數
1   劉彥宏  男   88  50  51  54  100  343  68.6  21.0       3        2
2   曾彥廷  男   54  92  60  50   76  332  66.4  28.0       2        3
3   吳子睿  男   63  85  50  96   71  365  73.0  12.0       1        4
4   蕭志明  男   61  53  64  94   45  317  63.4  32.0       2        3
5   王文傑  男   57  45  49  61   90  302  60.4  38.0       3        2
6   朱冠霖  男   67  54  71  59   89  340  68.0  24.0       2        3
7   謝欣蓉  女   80  67  92  41   47  327  65.4  29.0       2        3
8   羅淑芬  女   41  96  89  62   76  364  72.8  14.0       1        4
9   許美慧  女   96  98  93  54   46  387  77.4   8.0       2        3
10  廖志豪  男   62  67  40  72   49  290  58.0  47.0       2        3
11  葉柏翰  男   53  88  48  69   84  342  68.4  23.0       2        3
12  呂承恩  男   42  55  75  43   79  294  58.8  44.0       3        2
13  蘇雅婷  女   99  96  40  68   89  392  78.4   6.0       1        4
14  高浩宇  男   47  48  68  70   82  315  63.0  35.0       2        3
15  王婉茹  女   50  92  53  91   58  344  68.8  20.0       3        2
16  莊承翰  男   69  56  46  53   92  316  63.2  33.0       3        2
17  黃裕傑  男   58  60  73  53   65  309  61.8  37.0       2        3
18  王冠廷  男   54  73  45  45   41  258  51.6  49.0       4        1
19  呂婉慧  女   48  96  70  58   64  336  67.2  26.0       2        3
20  莊子謙  男   83  97  71  43   71  365  73.0  12.0       1        4
21  蘇彥宏  男  100  86  83  42   71  382  76.4   9.0       1        4
22  李柏融  男   58  80  58  53   73  322  64.4  31.0       3        2
23  曾明軒  男   98  61  88  72   69  388  77.6   7.0       0        5
24  呂佳瑩  女   90  89  61  41   80  361  72.2  15.0       1        4
25  洪怡君  女   66  64  62  53   91  336  67.2  26.0       1        4
26  洪柏宏  男   51  72  97  98   95  413  82.6   1.0       1        4
27  江雅琪  女   42  85  46  74   54  301  60.2  40.0       3        2
28  郭怡萱  女   83  68  88  96   42  377  75.4  11.0       1        4
29  簡婉慧  女   61  89  87  88   74  399  79.8   4.0       0        5
30  楊靜宜  女   51  59  44  92   97  343  68.6  21.0       3        2
31  曾靜儀  女   65  59  67  90   74  355  71.0  17.0       1        4
32  蕭怡伶  女   40  56  85  54   88  323  64.6  30.0       3        2
33  洪裕豪  男   64  51  42  67   68  292  58.4  46.0       2        3
34  簡建宏  男  100  62  74  71   74  381  76.2  10.0       0        5
35  劉浩然  男   47  58  90  65   56  316  63.2  33.0       3        2
36  蕭浩宇  男   77  45  89  60   66  337  67.4  25.0       1        4
37  呂怡靜  女   94  46  54  64   44  302  60.4  38.0       3        2
38  邱宗翰  男   53  96  66  47   99  361  72.2  15.0       2        3
39  彭美慧  女   75  47  95  89   96  402  80.4   3.0       1        4
40  劉靜芬  女   67  71  73  46   44  301  60.2  40.0       2        3
41  許淑芬  女   68  42  40  43   60  253  50.6  50.0       3        2
42  邱裕豪  男   41  59  65  60   42  267  53.4  48.0       3        2
43  吳雅萍  女   70  86  97  42   54  349  69.8  19.0       2        3
44  施子軒  男   69  61  58  69   43  300  60.0  42.0       2        3
45  莊柏融  男   60  75  72  52   54  313  62.6  36.0       2        3
46  鍾浩銘  男   99  91  95  74   54  413  82.6   1.0       1        4
47  周美玲  女   73  72  93  61   53  352  70.4  18.0       1        4
48  劉婉婷  女   88  91  62  60   93  394  78.8   5.0       0        5
49  曾明哲  男   47  72  75  47   55  296  59.2  43.0       3        2
50  詹柏翰  男   55  58  41  78   61  293  58.6  45.0       3        2

In [69]:
def get_failing_subjects(row):
    subjects = ['國文', '英文', '數學', '地理', '歷史']
    failing = [subj for subj in subjects if row[subj] < 60]    
    return ','.join(failing) if failing else "無"
    
    
scores_df["不及格的科目名稱"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(get_failing_subjects,axis=1)
scores_df

,姓名,性別,國文,英文,數學,地理,歷史,總分,平均,排名,及格的科目數,不及格的科目數,不及格的科目名稱
1,劉彥宏,男,88,50,51,54,100,343,68.6,21.0,3,2,"英文,數學,地理"
2,曾彥廷,男,54,92,60,50,76,332,66.4,28.0,2,3,"國文,地理"
3,吳子睿,男,63,85,50,96,71,365,73.0,12.0,1,4,數學
4,蕭志明,男,61,53,64,94,45,317,63.4,32.0,2,3,"英文,歷史"
5,王文傑,男,57,45,49,61,90,302,60.4,38.0,3,2,"國文,英文,數學"
6,朱冠霖,男,67,54,71,59,89,340,68.0,24.0,2,3,"英文,地理"
7,謝欣蓉,女,80,67,92,41,47,327,65.4,29.0,2,3,"地理,歷史"
8,羅淑芬,女,41,96,89,62,76,364,72.8,14.0,1,4,國文
9,許美慧,女,96,98,93,54,46,387,77.4,8.0,2,3,"地理,歷史"
10,廖志豪,男,62,67,40,72,49,290,58.0,47.0,2,3,"數學,歷史"
11,葉柏翰,男,53,88,48,69,84,342,68.4,23.0,2,3,"國文,數學"
12,呂承恩,男,42,55,75,43,79,294,58.8,44.0,3,2,"國文,英文,地理"
13,蘇雅婷,女,99,96,40,68,89,392,78.4,6.0,1,4,數學
14,高浩宇,男,47,48,68,70,82,315,63.0,35.0,2,3,"國文,英文"
15,王婉茹,女,50,92,53,91,58,344,68.8,20.0,3,2,"國文,數學,歷史"
16,莊承翰,男,69,56,46,53,92,316,63.2,33.0,3,2,"英文,數學,地理"
17,黃裕傑,男,58,60,73,53,65,309,61.8,37.0,2,3,"國文,地理"
18,王冠廷,男,54,73,45,45,41,258,51.6,49.0,4,1,"國文,數學,地理,歷史"
19,呂婉慧,女,48,96,70,58,64,336,67.2,26.0,2,3,"國文,地理"
20,莊子謙,男,83,97,71,43,71,365,73.0,12.0,1,4,地理
21,蘇彥宏,男,100,86,83,42,71,382,76.4,9.0,1,4,地理
22,李柏融,男,58,80,58,53,73,322,64.4,31.0,3,2,"國文,數學,地理"
23,曾明軒,男,98,61,88,72,69,388,77.6,7.0,0,5,無
24,呂佳瑩,女,90,89,61,41,80,361,72.2,15.0,1,4,地理
25,洪怡君,女,66,64,62,53,91,336,67.2,26.0,1,4,地理
26,洪柏宏,男,51,72,97,98,95,413,82.6,1.0,1,4,國文
27,江雅琪,女,42,85,46,74,54,301,60.2,40.0,3,2,"國文,數學,歷史"
28,郭怡萱,女,83,68,88,96,42,377,75.4,11.0,1,4,歷史
29,簡婉慧,女,61,89,87,88,74,399,79.8,4.0,0,5,無
30,楊靜宜,女,51,59,44,92,97,343,68.6,21.0,3,2,"國文,英文,數學"
31,曾靜儀,女,65,59,67,90,74,355,71.0,17.0,1,4,英文
32,蕭怡伶,女,40,56,85,54,88,323,64.6,30.0,3,2,"國文,英文,地理"
33,洪裕豪,男,64,51,42,67,68,292,58.4,46.0,2,3,"英文,數學"
34,簡建宏,男,100,62,74,71,74,381,76.2,10.0,0,5,無
35,劉浩然,男,47,58,90,65,56,316,63.2,33.0,3,2,"國文,英文,歷史"
36,蕭浩宇,男,77,45,89,60,66,337,67.4,25.0,1,4,英文
37,呂怡靜,女,94,46,54,64,44,302,60.4,38.0,3,2,"英文,數學,歷史"
38,邱宗翰,男,53,96,66,47,99,361,72.2,15.0,2,3,"國文,地理"
39,彭美慧,女,75,47,95,89,96,402,80.4,3.0,1,4,英文
40,劉靜芬,女,67,71,73,46,44,301,60.2,40.0,2,3,"地理,歷史"
41,許淑芬,女,68,42,40,43,60,253,50.6,50.0,3,2,"英文,數學,地理"
42,邱裕豪,男,41,59,65,60,42,267,53.4,48.0,3,2,"國文,英文,歷史"
43,吳雅萍,女,70,86,97,42,54,349,69.8,19.0,2,3,"地理,歷史"
44,施子軒,男,69,61,58,69,43,300,60.0,42.0,2,3,"數學,歷史"
45,莊柏融,男,60,75,72,52,54,313,62.6,36.0,2,3,"地理,歷史"
46,鍾浩銘,男,99,91,95,74,54,413,82.6,1.0,1,4,歷史
47,周美玲,女,73,72,93,61,53,352,70.4,18.0,1,4,歷史
48,劉婉婷,女,88,91,62,60,93,394,78.8,5.0,0,5,無
49,曾明哲,男,47,72,75,47,55,296,59.2,43.0,3,2,"國文,地理,歷史"
50,詹柏翰,男,55,58,41,78,61,293,58.6,45.0,3,2,"國文,英文,數學"