In [19]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40,101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))


#scores_df.T  #轉置

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values   #第一層[]是subscript,第二層[]才是list
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]   #變換欄位
#scores_df

#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]  #silce

     姓名 性別  國文  英文  數學  地理  歷史
6   朱冠霖  男  78  96  81  58  84
7   謝欣蓉  女  59  65  63  81  73
8   羅淑芬  女  49  49  66  78  71
9   許美慧  女  51  52  52  87  97
10  廖志豪  男  52  48  56  82  90

In [23]:
# 透過值來搜尋
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]
scores_df.query("性別 == '女' and 國文 < 60")

     姓名 性別  國文  英文  數學  地理  歷史
7   謝欣蓉  女  59  65  63  81  73
8   羅淑芬  女  49  49  66  78  71
9   許美慧  女  51  52  52  87  97
19  呂婉慧  女  59  52  65  55  68
25  洪怡君  女  40  63  58  61  70
43  吳雅萍  女  57  46  60  51  90
48  劉婉婷  女  40  42  85  87  44

In [34]:
# 統計
scores_df["總分"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)  # axis=1：橫向加總
scores_df["平均"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_df["排名"] = scores_df['總分'].rank(ascending = False, method = 'min')
scores_df.sort_values(by="排名")

     姓名 性別   國文  英文   數學   地理  歷史   總分    平均    排名
29  簡婉慧  女   88  93   84   81  91  437  87.4   1.0
35  劉浩然  男   90  88   91   77  80  426  85.2   2.0
20  莊子謙  男   77  94   73   89  89  422  84.4   3.0
5   王文傑  男   98  74   61   90  93  416  83.2   4.0
49  曾明哲  男   86  80   98  100  44  408  81.6   5.0
36  蕭浩宇  男   86  49   96   96  80  407  81.4   6.0
34  簡建宏  男   96  62   76   90  82  406  81.2   7.0
26  洪柏宏  男  100  95   59   80  71  405  81.0   8.0
30  楊靜宜  女   95  71   56   93  90  405  81.0   8.0
44  施子軒  男   81  70   65   97  91  404  80.8  10.0
39  彭美慧  女   87  90   68   76  80  401  80.2  11.0
1   劉彥宏  男   85  63   88   89  74  399  79.8  12.0
6   朱冠霖  男   78  96   81   58  84  397  79.4  13.0
11  葉柏翰  男   92  64  100   91  45  392  78.4  14.0
13  蘇雅婷  女   73  67   91   85  70  386  77.2  15.0
45  莊柏融  男   54  88   89   88  67  386  77.2  15.0
18  王冠廷  男   61  74   76   97  71  379  75.8  17.0
15  王婉茹  女   95  64   87   75  56  377  75.4  18.0
17  黃裕傑  男   68  84   81   97  46  376  75.2  19.0
3   吳子睿  男   86  72   43   75  99  375  75.0  20.0
27  江雅琪  女   74  98   72   73  57  374  74.8  21.0
33  洪裕豪  男   71  94   70   80  56  371  74.2  22.0
14  高浩宇  男   95  56   43   77  97  368  73.6  23.0
24  呂佳瑩  女   94  41   78   86  68  367  73.4  24.0
42  邱裕豪  男   78  54   95   80  53  360  72.0  25.0
21  蘇彥宏  男   82  91   53   72  56  354  70.8  26.0
2   曾彥廷  男   70  99   81   49  53  352  70.4  27.0
32  蕭怡伶  女   67  60   66   81  74  348  69.6  28.0
38  邱宗翰  男   86  63   61   89  45  344  68.8  29.0
47  周美玲  女   71  40   69   96  66  342  68.4  30.0
7   謝欣蓉  女   59  65   63   81  73  341  68.2  31.0
9   許美慧  女   51  52   52   87  97  339  67.8  32.0
37  呂怡靜  女   77  65   43   69  82  336  67.2  33.0
46  鍾浩銘  男   73  44   81   94  42  334  66.8  34.0
23  曾明軒  男   46  41   77   90  80  334  66.8  34.0
12  呂承恩  男   86  59   92   43  53  333  66.6  36.0
10  廖志豪  男   52  48   56   82  90  328  65.6  37.0
41  許淑芬  女  100  40   58   52  77  327  65.4  38.0
50  詹柏翰  男   98  56   42   53  68  317  63.4  39.0
40  劉靜芬  女   75  65   46   75  55  316  63.2  40.0
8   羅淑芬  女   49  49   66   78  71  313  62.6  41.0
4   蕭志明  男   87  64   52   64  45  312  62.4  42.0
16  莊承翰  男   56  62   46   91  54  309  61.8  43.0
28  郭怡萱  女   84  47   66   46  63  306  61.2  44.0
31  曾靜儀  女   60  49   50   71  75  305  61.0  45.0
43  吳雅萍  女   57  46   60   51  90  304  60.8  46.0
19  呂婉慧  女   59  52   65   55  68  299  59.8  47.0
22  李柏融  男   51  48   70   53  76  298  59.6  48.0
48  劉婉婷  女   40  42   85   87  44  298  59.6  48.0
25  洪怡君  女   40  63   58   61  70  292  58.4  50.0